#!/usr/bin/env bash
set -e

sudo apt-get update
sudo apt-get install -y --no-install-recommends python3.8 \
                                                python3.8-venv \
                                                python3.8-dev
