#!/bin/sh

set -x

REQ_DIR=requirements

compile () {
  local output
  output=${1:?required}
  shift

  uv pip compile \
    --universal \
    --no-strip-extras \
    --no-header \
    --annotate \
    --upgrade \
    --generate-hashes \
    --emit-index-url \
    $* --output-file $output pyproject.toml
}

python -m venv /tmp/venv-soufi
. /tmp/venv-soufi/bin/activate
pip install --upgrade --require-hashes \
    --disable-pip-version-check \
    -r ${REQ_DIR}/requirements-bootstrap.txt
rm -rf ${REQ_DIR}
mkdir -p ${REQ_DIR}

# Any/all switches must come after the output filename!
compile ${REQ_DIR}/requirements.txt
compile ${REQ_DIR}/requirements-test.txt --extra test
compile ${REQ_DIR}/requirements-bootstrap.txt --extra bootstrap
compile ${REQ_DIR}/requirements-cli.txt --extra cli
